# Generated by Django 5.2.14 on 2026-05-25 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=30, verbose_name='Nome da Categoria')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_negocio', models.CharField(max_length=150, verbose_name='Nome do Negócio')),
                ('segmento', models.CharField(max_length=30, verbose_name='Segmento')),
                ('meta_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Meta Mensal')),
                ('capital_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capital Inicial')),
            ],
            options={
                'verbose_name': 'Negócio',
                'verbose_name_plural': 'Negócios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Usuario')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('senha', models.CharField(max_length=120, verbose_name='Senha')),
                ('data_cadastro', models.DateField(verbose_name=' Data de Cadastro')),
                ('tipo_usuario', models.CharField(max_length=20, verbose_name=' Tipo de Usuario')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('prazo', models.DateField(verbose_name='Data')),
                ('descricao_meta', models.CharField(max_length=150, verbose_name='Descrição da Meta')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.negocio', verbose_name='Negócio')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
        migrations.CreateModel(
            name='IndicadorFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margem_lucro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Margem de Lucro')),
                ('ponto_equilibrio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Data')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.negocio', verbose_name='Negócio')),
            ],
            options={
                'verbose_name': 'Indicador Financeiro',
                'verbose_name_plural': 'Indicadores Financeiros',
            },
        ),
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total da Receita')),
                ('despesa_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Despesa total')),
                ('lucro_liquido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lucro Liquido')),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Final')),
                ('periodo', models.DateField(verbose_name='Periodo')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.negocio', verbose_name='Negócio')),
            ],
            options={
                'verbose_name': 'Fechamento Mensal',
                'verbose_name_plural': 'Fechamentos Mensais',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_despesa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_depesa', models.DateField(verbose_name='Data')),
                ('descricao_despesa', models.CharField(max_length=150, verbose_name='Descrição da Despesa')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categoria')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.negocio', verbose_name='Negócio')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Faturamento Mensal')),
                ('despesas_totais', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Despesas')),
                ('lucro_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lucro Total')),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Atual')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.negocio', verbose_name='Negócio')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=100, verbose_name='Mensagem')),
                ('data_alerta', models.DateField(verbose_name='Data')),
                ('prioridade', models.CharField(max_length=150, verbose_name='Prioridade')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.negocio', verbose_name='Negócio')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Valor')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da Venda')),
                ('estoque', models.CharField(max_length=100, verbose_name='Estoque')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categoria')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.negocio', verbose_name='Negócio')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição da Receita')),
                ('forma_pagamento', models.CharField(max_length=100, verbose_name='Forma de Pagamento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categoria')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.negocio', verbose_name='Negócio')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relatorio', models.CharField(max_length=25, verbose_name='Tipo de Relatório')),
                ('periodo', models.DateField(verbose_name='Periodo')),
                ('data_geracao', models.DateField(max_length=150, verbose_name='Data de Geração')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.negocio', verbose_name='Negócio')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=100, verbose_name='Nome')),
                ('custo_operacional', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Serviço')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categoria')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.negocio', verbose_name='Negócio')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Precificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('margem_lucros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Margem de lucro')),
                ('impostos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Impostos')),
                ('preco_final', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Preço Final')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto', verbose_name='Produto')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servico', verbose_name='Servico')),
            ],
            options={
                'verbose_name': 'Precificação',
                'verbose_name_plural': 'Precificações',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_notificacao', models.CharField(max_length=100, verbose_name='Notificação')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('status_notificacao', models.CharField(max_length=150, verbose_name='Status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.AddField(
            model_name='negocio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Nome do Usuário'),
        ),
    ]
