# Generated by Django 5.2.14 on 2026-06-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RenameField(
            model_name='despesa',
            old_name='data_depesa',
            new_name='data_despesa',
        ),
        migrations.AlterField(
            model_name='indicadorfinanceiro',
            name='ponto_equilibrio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ponto de Equilibrio'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='data_geracao',
            field=models.DateField(verbose_name='Data de Geração'),
        ),
    ]
