# Generated by Django 5.2.14 on 2026-06-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precificacao',
            old_name='margem_lucros',
            new_name='margem_lucro',
        ),
    ]
