# Generated by Codex on 2026-06-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_usuario_data_cadastro_alter_usuario_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precificacao",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.produto",
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="precificacao",
            name="servico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.servico",
                verbose_name="Servico",
            ),
        ),
    ]
