# Generated by Django 5.2.14 on 2026-06-20 12:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_precificacao_produto_alter_precificacao_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='aviso_antecipado_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='despesa',
            name='aviso_vencimento_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de vencimento'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='app.despesa', verbose_name='Despesa relacionada'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao_despesa',
            field=models.CharField(max_length=150, verbose_name='Descrição da despesa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(default='Pendente', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='mensagem_notificacao',
            field=models.CharField(max_length=255, verbose_name='Notificação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='status_notificacao',
            field=models.CharField(default='Não lida', max_length=150, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='notificacao',
            constraint=models.UniqueConstraint(fields=('despesa', 'tipo'), name='notificacao_unica_por_despesa_e_tipo'),
        ),
    ]
