# Generated by Django 5.2.14 on 2026-06-20 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_despesa_aviso_antecipado_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerta',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='alerta',
            name='periodo_referencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='status_alerta',
            field=models.CharField(default='Não lido', max_length=30),
        ),
        migrations.AddField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(default='Manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='mensagem',
            field=models.CharField(max_length=255, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='prioridade',
            field=models.CharField(default='Alta', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(fields=('negocio', 'tipo', 'periodo_referencia'), name='alerta_financeiro_unico_por_periodo'),
        ),
    ]
